# Generated by Django 5.0 on 2026-06-30 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=100)),
                ('max_hp', models.IntegerField(default=100)),
                ('attack', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=5)),
                ('exp_reward', models.IntegerField(default=50)),
                ('coin_reward', models.IntegerField(default=20)),
                ('is_boss', models.BooleanField(default=False)),
                ('sprite_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='maps.area')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('required_level', models.IntegerField(default=1)),
                ('enemy_ids', models.JSONField(default=list)),
                ('boss_id', models.IntegerField(blank=True, null=True)),
                ('reward_id', models.IntegerField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='chapters.chapter')),
            ],
            options={
                'ordering': ['chapter', 'order'],
                'unique_together': {('chapter', 'order')},
            },
        ),
        migrations.CreateModel(
            name='StageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('best_score', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='stages.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stage')},
            },
        ),
    ]
