# Generated by Django 5.0 on 2026-06-30 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('text', models.TextField()),
                ('choices', models.JSONField(blank=True, null=True)),
                ('next_dialogue_id', models.IntegerField(blank=True, null=True)),
                ('reward_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DialogueChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('next_dialogue_id', models.IntegerField(blank=True, null=True)),
                ('affinity_change', models.IntegerField(default=0)),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_set', to='dialogue.dialogue')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar_url', models.CharField(max_length=255)),
                ('affinity', models.IntegerField(default=0)),
                ('dialogues_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='maps.area')),
            ],
        ),
        migrations.AddField(
            model_name='dialogue',
            name='npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='dialogue.npc'),
        ),
        migrations.AlterUniqueTogether(
            name='dialogue',
            unique_together={('npc', 'order')},
        ),
        migrations.CreateModel(
            name='NPCAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity', models.IntegerField(default=0)),
                ('dialogues_completed', models.IntegerField(default=0)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_affinities', to='dialogue.npc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc_affinities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'npc')},
            },
        ),
    ]
