# Generated by Django 5.0 on 2026-06-30 03:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slot_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot_number'],
                'unique_together': {('user', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='SaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_key', models.CharField(max_length=100)),
                ('data_value', models.JSONField()),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('save_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_data', to='saves.saveslot')),
            ],
            options={
                'unique_together': {('save_slot', 'data_key')},
            },
        ),
    ]
