[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:backend]
command=uvicorn api.main:app --host 0.0.0.0 --port 8000 --workers 4
directory=/app/backend
user=root
autostart=true
autorestart=true
startretries=3
redirect_stderr=true
stdout_logfile=/var/log/backend.log
stderr_logfile=/var/log/backend_error.log

[program:redis]
command=redis-server
directory=/usr/local/bin
user=root
autostart=true
autorestart=true
startretries=3
redirect_stderr=true
stdout_logfile=/var/log/redis.log
stderr_logfile=/var/log/redis_error.log

[program:nginx]
command=nginx -g "daemon off;"
directory=/etc/nginx
user=root
autostart=true
autorestart=true
startretries=3
redirect_stderr=true
stdout_logfile=/var/log/nginx.log
stderr_logfile=/var/log/nginx_error.log

[program:daphne]
command=daphne -b 0.0.0.0 -p 8001 campus_daze.asgi:application
directory=/app/backend/django
user=root
autostart=true
autorestart=true
startretries=3
redirect_stderr=true
stdout_logfile=/var/log/daphne.log
stderr_logfile=/var/log/daphne_error.log