# Generated by Django 5.0 on 2026-06-30 03:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('condition_type', models.CharField(max_length=50)),
                ('condition_value', models.IntegerField()),
                ('reward_id', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coin_amount', models.IntegerField(default=0)),
                ('exp_amount', models.IntegerField(default=0)),
                ('cat_food_amount', models.IntegerField(default=0)),
                ('skill_book_id', models.IntegerField(blank=True, null=True)),
                ('equipment_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.IntegerField()),
                ('difficulty', models.IntegerField(default=1)),
                ('order', models.IntegerField()),
                ('required_level', models.IntegerField(default=1)),
                ('objectives', models.JSONField()),
                ('reward_id', models.IntegerField(blank=True, null=True)),
                ('next_task_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_id', models.IntegerField()),
                ('result', models.IntegerField(default=0)),
                ('turn_count', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='RestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('coins_earned', models.IntegerField(default=0)),
                ('exp_earned', models.IntegerField(default=0)),
                ('cat_food_earned', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_records', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_achievements', to='gameplay.achievement')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='characters.character')),
            ],
            options={
                'unique_together': {('character', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='characters.character')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='gameplay.task')),
            ],
            options={
                'unique_together': {('character', 'task')},
            },
        ),
    ]
