# Generated by Django 5.0 on 2026-06-30 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cat_type', models.CharField(max_length=50)),
                ('personality', models.CharField(max_length=100)),
                ('battle_role', models.CharField(max_length=50)),
                ('base_hp', models.IntegerField(default=100)),
                ('base_attack', models.IntegerField(default=10)),
                ('base_defense', models.IntegerField(default=5)),
                ('base_agility', models.IntegerField(default=5)),
                ('base_intelligence', models.IntegerField(default=5)),
                ('sprite_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slot', models.IntegerField()),
                ('rarity', models.IntegerField(default=1)),
                ('attack_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('hp_bonus', models.IntegerField(default=0)),
                ('mp_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('skill_bonus', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('damage', models.IntegerField(default=0)),
                ('mp_cost', models.IntegerField(default=10)),
                ('cooldown', models.IntegerField(default=0)),
                ('range', models.IntegerField(default=1)),
                ('skill_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=100)),
                ('max_hp', models.IntegerField(default=100)),
                ('mp', models.IntegerField(default=50)),
                ('max_mp', models.IntegerField(default=50)),
                ('attack', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=5)),
                ('agility', models.IntegerField(default=5)),
                ('intelligence', models.IntegerField(default=5)),
                ('current_form', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='characters.charactertemplate')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='characters.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='characters.character')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='characters.equipmenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('cooldown_remaining', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='characters.character')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='characters.skilltemplate')),
            ],
        ),
    ]
